### PR TITLE
Maturing the API

### PR DESCRIPTION
**Pull request by dhensby**
This signifies a substantial re-write of the library to more completely follow the [httpbis message signatures specification](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-message-signature).

Approach:

There are two main functions, `signMessage()` and `verifyMessage()`. Each accepts: a config to dictate some parameters for the signing/verification logic; a message (to be signed); [optionally] a third message (the request to bind to if signing a response and binding is required).

Signing Config:

 - key: The signing key to sign your request with
 - name: [optional] The name of the signature in the Signature and Signature-Input headers - collisions are automatically avoided
 - params: [optional] A list of the parameters to include in the signature (eg: created, expires, etc)
 - fields: [optional] A list of fields to sign, these can either be derived components or headers or a "structured field" to indicate encoding or other properties of the component to be signed.
 - paramValues: [optional] The parameter values to use instead of allowing the library to determine them itself, eg: specify a `created` or `expires` time if you want your own one.

Verifying Config:

 - verifier: The verifier callback
 - tolerance: [optional] A clock tolerance for the time comparisons (in seconds). default: 0
 - notAfter: [optional] Dictates a maximum date for the created key - this stops us validating signatures that are too old. default: Date.now() + tolerance
 - maxAge: [optional] Essentially overrides the expires time on the signature - if provided we won't validate signatures that are older than this time (seconds).
 - requiredParams: [optional] A list of parameters that *must* be signed for us to consider the signature valid
 - requiredFields: [optional] A list of derived components/headers that *must* be signed for us to consider the signature valid
 - all: [optional] Require all signature to validate (default: false) - NB: If a message has multiple signatures, it is expected that a party validating the signature only cares about the signatures that it *can* validate (ie: ones where it knows the keyid), as those are trusted keys. Other signatures may have been added by other applications that the current verifier has no knowledge of (and thus no access to the key to perform validation) so they can be ignored whilst still validating the signature. In some circumstances where the application is prepared to tightly couple with logic around expected signatures, this flag can be used to force errors if there is any signature that either can't be validated because it came from an unknown source or because it is invalid. This is raised in [section 7.2.6](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-message-signatures-13#section-7.2.6)

This includes full support for:

 - Signing and verification of requests and responses
 - [Request-response bound signatures](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-message-signatures#section-2.4)
 - Full support of the derived components, including `@query-param` type (which was previously not supported), and header encoding rules.
 - Added ed25519 key support and also `rsa-sha1` signatures (as per the legacy spec).

Outstanding items:

 - [x] Add an ability for consumers of the library to provide a component parser. The specification leaves open the ability to add components to signatures that are not (yet) defined in the specification. It's important that the application can parse these and act on them as required. It's also important that, if consumers of the library want to rely on a newly defined component, but the library is not updated fast enough, they can add support for these without needing the upstream library to be updated.
 - [x] A bit of consideration needs to be given to how consumers look up the key to perform verification with
 - [ ] A bit more code tidying - I think there's a bit too much repeated encoding/decoding of the structured headers and this could probably be made more efficient/streamlined.
 - [ ] Guidance/planning on how to correctly build the `url` parameter for incoming requests (perhaps a function that can do this from a raw `IncomingMessage` object)
 - [ ] Go through the spec again making sure that any MUST items are followed appropriately and any examples are followed
 - [x] Proper integration tests, including actual HTTP requests/responses (run a HTTP server as part of tests and actually assert it works)
 - [ ] Documentation! Proper documentation of the API plus examples of how to sign and verify requests

Possible future improvements (out of scope of the rewrite):

 - It may be useful if, when validating request/response message signatures, that the library return a "new" request that only includes the signed values of the request - ie: a "trusted" message is returned, preventing the application from accidentally processing untrusted headers/values. There may be a need to provide a list of "always trusted" headers (eg: content-type) for operational purposes but ideally there would be agreement between parties that these operationally required headers be signed ahead of time. see https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-message-signatures#section-7.2.1
 - Rather than trying to validate all signatures in a message, the consumer could provide a filtering function that determines if the signature should be processed at all (eg: by looking up a keyid in a list of known keys), thus preventing signatures that could cause an error from breaking the validation of a good signature. - EDIT: This is essentially done and the job of the `keyLookup` function - it can throw errors or return null based on the signature params provided.
 - `Accept-Signature` support - The `Accept-Signature` header could be used to "automatically" configure signing. By parsing this header we can determine:
 - Required fields to be signed, required parameters to use (eg: keyid, alg, nonce, name), and even multiple signatures. - EDIT: done

### CODE REVIEW

**Comment by dhensby** [comment]
A checklist from the specification (note they only just released an update: https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-message-signatures-13)

### High level requirements of a HTTP Message Signing Application/Library (see [Section 1.4](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-message-signatures#section-1.4) of spec):

- [ ] Allow specification of required/expected component identifiers
- [ ] Allow specification of required/expected signature parameters
- [ ] Be able to retrieve keys to verify the signature (eg: by keyid param)
- [ ] Be able to determine signature algorithms (eg: by alg param)
- [ ] Able to reject signatures that are signed with inappropriate algorithms for the key in hand
- [ ] Be able to determine the "context" for a signature and derive components from it

**Comment by dhensby** [comment]
After going through the specification further and thinking of use cases where multiple signatures may be added to message

**Comment by adrianhopebailie** [comment]
Awesome work!

**Comment by dhensby** [comment]
I'm going to take this in as is, and then other improvements can come later

**Pull request merged**
